theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp2s0"
interval = 5

[[block]]
block = "net"
device = "eno1"
interval = 5

[[block]]
block = "temperature"
interval = 10
collapsed = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MFg}%"
format_swap = "{MFp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "1 min avg: {1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %Y-%m-%d %H:%M:%S"
